apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    env: development
resources:
- ../../base
images:
  - name: my-app
    newName: my-app
    newTag: v1
